# standard jekyll configuration
markdown:         kramdown
highlighter:      rouge
paginate:         10     # the number of post per page
#permalink:        /:year/:month/:day/:title.html
permalink:        /:title.html
safe:             true
lsi:              false
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
gems:
    - jemoji

# configuration required for some pages
title:            Fan's Math World
description:      感受数学之美
author:
    name:         Fan Hongtao
    email:        fanhongtao@gmail.com

# configuration for ehancements, uncomment to enable
github:
    username: fanhongtao

categories_path: category.html
tags_path: tag.html
# rss_path: feed.xml
